insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (1, 'Aymer', 'Korejs', 'Quality Control Specialist', '2026-01-02', 238);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (2, 'Avrit', 'Hallibone', 'Associate Professor', '2025-10-19', 481);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (3, 'Darby', 'Strong', 'VP Quality Control', '2026-02-21', 249);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (4, 'Shannon', 'Hedde', 'Business Systems Development Analyst', '2025-05-21', 111);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (5, 'Cully', 'Kenwell', 'Geological Engineer', '2025-11-09', 157);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (6, 'Junie', 'Campos', 'Mechanical Systems Engineer', '2025-06-13', 352);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (7, 'Kitti', 'Pesticcio', 'VP Accounting', '2025-10-11', 98);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (8, 'Norma', 'Girauld', 'Media Manager II', '2025-06-08', 14);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (9, 'Ty', 'Durno', 'Graphic Designer', '2025-12-31', 420);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (10, 'Virgilio', 'Sonnenschein', 'General Manager', '2025-06-05', 223);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (11, 'Rollins', 'Monument', 'Nurse', '2025-06-25', 422);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (12, 'Osgood', 'Ricold', 'Product Engineer', '2025-04-12', 357);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (13, 'Bernard', 'Ferenczy', 'Software Test Engineer IV', '2025-06-05', 296);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (14, 'Haley', 'Braben', 'VP Sales', '2025-06-06', 300);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (15, 'Netti', 'Buckeridge', 'Technical Writer', '2025-03-20', 127);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (16, 'Denni', 'Calcut', 'VP Marketing', '2025-11-04', 399);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (17, 'Meridith', 'Akenhead', 'Registered Nurse', '2025-06-21', 18);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (18, 'Johnny', 'Glazebrook', 'Account Coordinator', '2025-09-23', 77);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (19, 'Noe', 'Galloway', 'Nuclear Power Engineer', '2025-05-15', 295);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (20, 'Aarika', 'Bleier', 'Database Administrator II', '2025-10-29', 99);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (21, 'Enriqueta', 'Magee', 'Tax Accountant', '2025-07-21', 140);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (22, 'Viole', 'Palley', 'Computer Systems Analyst III', '2025-03-27', 95);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (23, 'Rosalyn', 'Ruggen', 'Speech Pathologist', '2025-12-04', 227);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (24, 'Karilynn', 'Cankett', 'Director of Sales', '2026-01-12', 338);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (25, 'Rea', 'Campagne', 'Graphic Designer', '2025-05-07', 190);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (26, 'Leroi', 'Gahan', 'Senior Sales Associate', '2025-12-08', 425);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (27, 'Alisha', 'Djordjevic', 'Food Chemist', '2026-01-09', 453);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (28, 'Lanna', 'Tewkesbury', 'Food Chemist', '2025-07-14', 408);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (29, 'Olia', 'Messer', 'Nurse Practicioner', '2025-04-30', 387);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (30, 'Leonora', 'Sharphouse', 'Director of Sales', '2025-09-30', 99);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (31, 'Annabella', 'Ceschini', 'Financial Advisor', '2025-12-30', 326);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (32, 'Nickey', 'Chimenti', 'Sales Associate', '2025-03-20', 44);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (33, 'Zenia', 'Adiscot', 'Design Engineer', '2025-03-31', 202);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (34, 'Carley', 'Dimanche', 'Actuary', '2025-05-17', 185);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (35, 'Cleon', 'Kemme', 'Assistant Media Planner', '2026-02-26', 449);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (36, 'Jessamine', 'Phizacklea', 'Human Resources Manager', '2026-01-03', 431);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (37, 'Lesley', 'Urlich', 'Associate Professor', '2025-05-21', 293);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (38, 'Bondon', 'Kerner', 'Office Assistant IV', '2025-11-10', 341);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (39, 'Shannon', 'Blaszczynski', 'Community Outreach Specialist', '2025-04-05', 463);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (40, 'Romy', 'Fassbender', 'Senior Editor', '2025-08-20', 68);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (41, 'Kristopher', 'Sawford', 'Senior Financial Analyst', '2025-09-25', 397);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (42, 'Colly', 'Houseago', 'Chemical Engineer', '2025-12-22', 405);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (43, 'Raimondo', 'Dines', 'Marketing Manager', '2025-06-16', 494);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (44, 'Tallou', 'Schankel', 'Research Assistant III', '2025-04-28', 48);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (45, 'Currey', 'Carr', 'Staff Accountant III', '2025-07-23', 267);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (46, 'Torr', 'Knibbs', 'VP Accounting', '2025-03-28', 498);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (47, 'Rickard', 'Thay', 'Chemical Engineer', '2026-01-01', 347);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (48, 'Aubrie', 'Millmore', 'Programmer I', '2025-09-28', 473);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (49, 'Adrianne', 'Walshaw', 'Paralegal', '2025-11-01', 198);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (50, 'Frederick', 'Cockrell', 'Programmer Analyst II', '2025-03-28', 336);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (51, 'Englebert', 'Denes', 'Speech Pathologist', '2026-02-15', 384);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (52, 'Laurice', 'Foli', 'Chemical Engineer', '2025-11-09', 458);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (53, 'Ursola', 'Mountford', 'Financial Analyst', '2025-03-21', 327);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (54, 'Florella', 'Ferie', 'Technical Writer', '2025-05-31', 207);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (55, 'Alberta', 'Cawt', 'Office Assistant II', '2025-03-22', 101);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (56, 'Paulette', 'McCreath', 'Budget/Accounting Analyst II', '2025-08-03', 459);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (57, 'Ganny', 'Edmeads', 'Analog Circuit Design manager', '2025-11-05', 433);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (58, 'Lydie', 'Netherclift', 'Mechanical Systems Engineer', '2025-08-15', 55);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (59, 'Jon', 'Rhucroft', 'Data Coordinator', '2025-11-27', 311);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (60, 'Farrand', 'Danat', 'Information Systems Manager', '2025-11-23', 446);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (61, 'Victoria', 'Dale', 'Assistant Manager', '2026-02-12', 228);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (62, 'Adrea', 'O''Lunny', 'Information Systems Manager', '2026-01-31', 268);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (63, 'Susanna', 'Rosenberg', 'Compensation Analyst', '2025-07-11', 409);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (64, 'Camille', 'Tatershall', 'Financial Analyst', '2026-01-20', 427);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (65, 'Kele', 'Shulver', 'Administrative Officer', '2025-03-27', 320);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (66, 'Hastings', 'Cottier', 'Account Executive', '2025-07-24', 410);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (67, 'Karoline', 'Gaisford', 'Help Desk Operator', '2025-04-18', 480);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (68, 'Rice', 'Shillitoe', 'Structural Engineer', '2025-12-06', 271);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (69, 'Estelle', 'Sondland', 'Executive Secretary', '2025-05-24', 431);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (70, 'Madlen', 'Salkeld', 'Recruiter', '2025-06-04', 60);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (71, 'Ferne', 'Izatson', 'Quality Control Specialist', '2025-10-24', 61);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (72, 'Perri', 'Frodsham', 'Help Desk Technician', '2025-06-24', 206);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (73, 'Coralyn', 'Randles', 'Senior Financial Analyst', '2026-01-26', 420);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (74, 'Ciel', 'Corkill', 'Occupational Therapist', '2025-09-27', 336);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (75, 'Cherri', 'Bachellier', 'Internal Auditor', '2025-08-18', 244);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (76, 'Price', 'Twist', 'Pharmacist', '2025-05-12', 346);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (77, 'Thelma', 'Clist', 'Geologist I', '2025-06-27', 10);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (78, 'Sukey', 'Antham', 'Legal Assistant', '2026-01-20', 488);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (79, 'Irena', 'Pell', 'Help Desk Operator', '2025-06-22', 235);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (80, 'Fernandina', 'Jepperson', 'Junior Executive', '2025-05-22', 122);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (81, 'Maddy', 'McCromley', 'VP Accounting', '2025-06-16', 14);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (82, 'Pat', 'Marzella', 'VP Product Management', '2025-06-09', 382);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (83, 'Audra', 'Djordjevic', 'Registered Nurse', '2025-12-05', 161);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (84, 'Aubert', 'Oldacres', 'Director of Sales', '2025-05-17', 219);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (85, 'Josefa', 'Drabble', 'Account Representative I', '2026-02-10', 430);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (86, 'Norri', 'Weeke', 'Senior Sales Associate', '2025-10-20', 301);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (87, 'Bartholomeo', 'Garatty', 'Programmer Analyst I', '2025-05-05', 261);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (88, 'Mollie', 'Yakuntsov', 'Recruiter', '2026-01-01', 77);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (89, 'Tessi', 'Garn', 'Structural Analysis Engineer', '2026-01-16', 326);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (90, 'Chevalier', 'Gurling', 'Mechanical Systems Engineer', '2025-06-12', 199);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (91, 'Bink', 'Portlock', 'Staff Accountant I', '2025-05-09', 384);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (92, 'Perkin', 'Jollie', 'VP Quality Control', '2025-03-29', 177);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (93, 'Aland', 'Drinkel', 'Software Engineer II', '2025-07-27', 120);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (94, 'Wit', 'Saterweyte', 'GIS Technical Architect', '2025-11-20', 386);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (95, 'Sallyanne', 'Claydon', 'Compensation Analyst', '2025-04-21', 137);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (96, 'Darelle', 'Poge', 'Sales Associate', '2025-03-22', 357);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (97, 'Denver', 'O'' Kelleher', 'Help Desk Operator', '2025-04-09', 71);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (98, 'Jasmine', 'Jesty', 'Software Engineer III', '2025-05-30', 41);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (99, 'Anastassia', 'Leneve', 'Occupational Therapist', '2025-11-02', 221);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (100, 'Ileane', 'Fettiplace', 'Structural Engineer', '2025-05-24', 272);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (101, 'Niel', 'Hazeltine', 'Editor', '2025-08-14', 458);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (102, 'Cybil', 'Inchboard', 'Marketing Manager', '2026-01-26', 321);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (103, 'Honey', 'Preston', 'Accounting Assistant I', '2025-09-15', 280);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (104, 'Lyda', 'Elfitt', 'Community Outreach Specialist', '2026-02-14', 237);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (105, 'Georges', 'Hlavecek', 'Health Coach IV', '2025-04-15', 32);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (106, 'Maggie', 'Simes', 'Payment Adjustment Coordinator', '2026-02-25', 26);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (107, 'Lily', 'Kisbey', 'Engineer II', '2025-10-11', 159);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (108, 'Lilah', 'Andraud', 'Account Coordinator', '2025-05-30', 159);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (109, 'Nonna', 'Matteotti', 'Chief Design Engineer', '2026-03-01', 328);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (110, 'Ivett', 'Winter', 'Accountant I', '2026-01-18', 32);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (111, 'Bowie', 'Simmins', 'Budget/Accounting Analyst IV', '2025-11-20', 300);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (112, 'Kevyn', 'Motto', 'Physical Therapy Assistant', '2025-11-10', 190);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (113, 'Konstantin', 'Hewlings', 'Geologist II', '2026-02-05', 20);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (114, 'Hasheem', 'Graser', 'Legal Assistant', '2026-01-19', 123);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (115, 'Celesta', 'Ambrosoli', 'Electrical Engineer', '2025-09-01', 363);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (116, 'Gar', 'Hedylstone', 'Sales Representative', '2025-09-28', 350);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (117, 'Stirling', 'Worsnip', 'Developer IV', '2025-08-15', 293);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (118, 'Madeleine', 'Leftley', 'Automation Specialist III', '2025-11-13', 328);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (119, 'Rockwell', 'Roblin', 'Software Test Engineer II', '2025-05-27', 4);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (120, 'Beaufort', 'La Batie', 'Associate Professor', '2025-09-13', 301);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (121, 'Ami', 'Frame', 'Editor', '2025-10-18', 399);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (122, 'Dorotea', 'Faloon', 'Dental Hygienist', '2026-03-02', 104);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (123, 'Beatrice', 'Northfield', 'Automation Specialist IV', '2025-04-16', 292);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (124, 'Nikki', 'Aldington', 'Programmer Analyst II', '2025-10-05', 288);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (125, 'Sigismundo', 'Peatman', 'Desktop Support Technician', '2025-08-28', 367);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (126, 'Ade', 'O'' Meara', 'Biostatistician I', '2026-01-06', 80);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (127, 'Katherine', 'Simonitto', 'Geological Engineer', '2026-02-19', 22);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (128, 'Kippy', 'Zukerman', 'Recruiting Manager', '2026-01-13', 106);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (129, 'Saidee', 'Corzon', 'Human Resources Manager', '2025-10-04', 213);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (130, 'Michael', 'Blofield', 'Operator', '2026-02-04', 371);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (131, 'Barris', 'Fabri', 'Information Systems Manager', '2026-02-02', 264);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (132, 'Oona', 'Iacomi', 'Research Associate', '2025-09-29', 267);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (133, 'Shel', 'Picken', 'Librarian', '2025-11-30', 155);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (134, 'Wanda', 'Shepland', 'Occupational Therapist', '2025-07-26', 245);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (135, 'Jay', 'Gouldsmith', 'Electrical Engineer', '2025-09-25', 124);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (136, 'Seward', 'Mahoney', 'Geologist II', '2026-01-24', 306);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (137, 'Lucilia', 'Curtis', 'Software Engineer II', '2025-04-03', 494);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (138, 'Klaus', 'Fenkel', 'Administrative Assistant I', '2025-04-16', 292);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (139, 'Tirrell', 'Clarabut', 'Help Desk Operator', '2025-07-07', 436);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (140, 'Diena', 'Paulich', 'Mechanical Systems Engineer', '2025-10-21', 470);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (141, 'Oralla', 'Gheorghe', 'Civil Engineer', '2025-10-11', 463);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (142, 'Gerti', 'Galpen', 'Assistant Manager', '2025-09-03', 254);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (143, 'Tamarra', 'Crooke', 'Tax Accountant', '2025-12-27', 389);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (144, 'Jenica', 'Klagges', 'General Manager', '2025-09-06', 238);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (145, 'Hendrik', 'Morrilly', 'Paralegal', '2025-07-29', 104);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (146, 'Thain', 'Fantin', 'Associate Professor', '2025-06-13', 475);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (147, 'Kial', 'Drewitt', 'Software Engineer II', '2026-01-12', 222);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (148, 'Vitoria', 'Beckey', 'Web Designer I', '2025-05-29', 331);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (149, 'Gerhardine', 'Filipchikov', 'Technical Writer', '2025-07-21', 321);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (150, 'Elvyn', 'Dundendale', 'VP Product Management', '2026-02-24', 106);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (151, 'Georgeta', 'Burbank', 'Analyst Programmer', '2025-05-02', 406);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (152, 'Jereme', 'Levicount', 'Financial Analyst', '2025-06-20', 334);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (153, 'Farica', 'Pierrepoint', 'VP Sales', '2025-08-03', 351);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (154, 'Anestassia', 'Ilyunin', 'Budget/Accounting Analyst III', '2026-03-10', 479);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (155, 'Carolann', 'Micka', 'Quality Control Specialist', '2025-04-14', 197);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (156, 'Letisha', 'MacCrann', 'Civil Engineer', '2025-07-15', 343);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (157, 'Duane', 'Leivers', 'Media Manager IV', '2025-06-08', 69);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (158, 'Roma', 'Jeannenet', 'Safety Technician III', '2025-03-27', 226);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (159, 'Carlyle', 'Ceely', 'Project Manager', '2025-08-12', 260);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (160, 'Trenna', 'Basilio', 'Director of Sales', '2025-09-13', 456);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (161, 'Hieronymus', 'McLise', 'Desktop Support Technician', '2025-08-27', 126);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (162, 'Kala', 'Knifton', 'Cost Accountant', '2025-10-31', 398);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (163, 'Rosalyn', 'Paolillo', 'Analyst Programmer', '2025-04-18', 457);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (164, 'Valencia', 'Rebanks', 'Environmental Specialist', '2025-06-23', 95);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (165, 'Gretal', 'O''Deoran', 'Technical Writer', '2025-10-29', 219);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (166, 'Felic', 'Bauldrey', 'Junior Executive', '2025-06-29', 88);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (167, 'Gerry', 'Ilieve', 'Junior Executive', '2025-09-30', 407);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (168, 'Cathrine', 'Martinovsky', 'Media Manager III', '2025-03-27', 46);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (169, 'Esther', 'Spencock', 'Project Manager', '2025-08-24', 234);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (170, 'Davey', 'Rickesies', 'Senior Financial Analyst', '2026-02-27', 125);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (171, 'Katherine', 'Pullin', 'Research Assistant I', '2025-08-17', 377);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (172, 'Bili', 'Ritch', 'Recruiter', '2025-04-10', 415);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (173, 'Ignaz', 'Haston', 'Assistant Media Planner', '2025-09-10', 458);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (174, 'Ranna', 'Bolin', 'Systems Administrator IV', '2025-09-07', 269);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (175, 'Georgeta', 'Speakman', 'Electrical Engineer', '2026-02-27', 348);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (176, 'Catherine', 'Allain', 'Senior Quality Engineer', '2026-01-07', 31);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (177, 'Nicolette', 'Fritzer', 'Recruiter', '2025-06-14', 221);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (178, 'Moira', 'Scamwell', 'Chemical Engineer', '2025-10-10', 329);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (179, 'Somerset', 'Shawl', 'Account Executive', '2026-01-26', 72);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (180, 'Rutter', 'Arthy', 'Marketing Manager', '2025-09-23', 71);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (181, 'Whittaker', 'Dewick', 'Biostatistician IV', '2025-05-20', 329);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (182, 'Shannan', 'Wais', 'Electrical Engineer', '2025-07-14', 35);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (183, 'Maximo', 'Kimbell', 'Software Engineer IV', '2025-11-21', 369);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (184, 'Evered', 'Drane', 'Software Test Engineer IV', '2025-12-15', 485);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (185, 'Dylan', 'Dudderidge', 'Mechanical Systems Engineer', '2025-12-22', 373);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (186, 'Mercy', 'McGillecole', 'Community Outreach Specialist', '2026-01-16', 474);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (187, 'Nari', 'Dampier', 'Analyst Programmer', '2026-01-30', 405);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (188, 'Lezley', 'Pridgeon', 'Computer Systems Analyst I', '2025-08-03', 210);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (189, 'Lydia', 'Rush', 'Project Manager', '2026-03-10', 36);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (190, 'Quincey', 'Rawlin', 'VP Sales', '2025-09-23', 336);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (191, 'Rodi', 'Padefield', 'Senior Quality Engineer', '2026-02-27', 484);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (192, 'Noland', 'Tuckie', 'Web Developer IV', '2025-06-10', 66);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (193, 'Sherrie', 'Bardill', 'Quality Engineer', '2025-06-28', 310);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (194, 'Garfield', 'Braunlein', 'Professor', '2025-10-23', 278);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (195, 'Kathlin', 'Armand', 'Pharmacist', '2026-02-20', 61);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (196, 'Ivonne', 'Cherrison', 'Speech Pathologist', '2025-04-01', 30);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (197, 'Maureene', 'Tebbut', 'Analog Circuit Design manager', '2025-05-29', 246);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (198, 'Margo', 'Stannett', 'Mechanical Systems Engineer', '2025-10-10', 98);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (199, 'Perry', 'Garton', 'Office Assistant II', '2025-05-08', 91);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (200, 'Jim', 'Edrich', 'Systems Administrator IV', '2026-02-20', 369);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (201, 'Cicily', 'Marnes', 'Marketing Assistant', '2025-05-17', 215);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (202, 'Abby', 'Laight', 'Office Assistant I', '2025-04-23', 401);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (203, 'Chantal', 'Dauncey', 'Systems Administrator IV', '2025-04-15', 299);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (204, 'Mayer', 'Itskovitz', 'Sales Associate', '2025-12-25', 194);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (205, 'Glyn', 'Ladel', 'Nurse Practicioner', '2025-07-07', 483);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (206, 'Garald', 'O''Scanlan', 'Design Engineer', '2025-04-28', 146);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (207, 'Ludovika', 'Vassano', 'Analog Circuit Design manager', '2025-06-13', 125);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (208, 'Demetrius', 'Rove', 'Occupational Therapist', '2025-09-20', 304);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (209, 'Crysta', 'Thurman', 'Assistant Media Planner', '2025-10-09', 409);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (210, 'Karola', 'Willey', 'Occupational Therapist', '2025-04-28', 290);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (211, 'Pietro', 'Wolfenden', 'Engineer II', '2025-09-16', 29);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (212, 'Elvyn', 'Kringe', 'General Manager', '2025-12-19', 156);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (213, 'Howey', 'Gait', 'Graphic Designer', '2026-01-16', 299);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (214, 'Stephannie', 'Roggers', 'Community Outreach Specialist', '2025-12-30', 253);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (215, 'Florencia', 'Page', 'Project Manager', '2025-07-22', 246);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (216, 'Chrissie', 'Menezes', 'Graphic Designer', '2025-05-03', 405);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (217, 'Ransell', 'Bonnett', 'Web Designer III', '2025-12-10', 425);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (218, 'Glendon', 'Townrow', 'Software Consultant', '2026-03-08', 344);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (219, 'Roderic', 'Harcase', 'Quality Control Specialist', '2025-09-26', 324);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (220, 'Blondelle', 'Durtnall', 'Clinical Specialist', '2025-07-01', 157);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (221, 'Clarita', 'Peake', 'Marketing Assistant', '2026-01-15', 64);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (222, 'Brennen', 'Ruggles', 'Help Desk Technician', '2025-09-10', 112);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (223, 'Klaus', 'Dulake', 'Community Outreach Specialist', '2025-06-19', 247);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (224, 'Denny', 'Riches', 'VP Accounting', '2025-12-14', 498);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (225, 'Padget', 'Devote', 'Recruiter', '2026-03-08', 121);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (226, 'Sherm', 'Gally', 'Structural Analysis Engineer', '2025-12-20', 103);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (227, 'John', 'Romayne', 'Media Manager I', '2025-11-03', 183);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (228, 'Aldous', 'Greser', 'Structural Engineer', '2025-12-13', 233);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (229, 'Jayme', 'Antoshin', 'Statistician I', '2025-05-04', 71);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (230, 'Rafaelita', 'Aves', 'Human Resources Assistant IV', '2026-03-03', 176);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (231, 'Elinor', 'Hasty', 'Web Developer I', '2025-04-21', 136);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (232, 'Glen', 'Gildroy', 'Compensation Analyst', '2025-10-09', 237);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (233, 'Florina', 'Claffey', 'Graphic Designer', '2026-01-05', 337);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (234, 'Omero', 'Van der Brug', 'Operator', '2025-09-07', 497);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (235, 'Tera', 'Fairbard', 'Structural Engineer', '2025-09-15', 201);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (236, 'Donnamarie', 'Petit', 'Structural Analysis Engineer', '2025-10-15', 489);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (237, 'Chaunce', 'Devil', 'Structural Engineer', '2025-07-17', 110);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (238, 'Gillian', 'Layus', 'Nurse Practicioner', '2025-06-13', 266);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (239, 'Lacy', 'Northidge', 'Environmental Specialist', '2025-12-31', 487);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (240, 'Gracia', 'Aleksandrev', 'Programmer Analyst I', '2025-04-23', 281);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (241, 'Aileen', 'Gentric', 'Sales Representative', '2026-02-12', 258);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (242, 'Agata', 'Stopher', 'VP Accounting', '2025-05-05', 451);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (243, 'Matthias', 'Mahaffey', 'General Manager', '2025-07-03', 331);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (244, 'Ali', 'Scheffler', 'Product Engineer', '2025-06-28', 126);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (245, 'Candice', 'Krysiak', 'Design Engineer', '2025-08-23', 165);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (246, 'Ferdinand', 'Menure', 'VP Quality Control', '2025-12-27', 290);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (247, 'Veronike', 'Beranek', 'Junior Executive', '2025-06-26', 227);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (248, 'Grazia', 'Kilshall', 'Programmer Analyst III', '2025-06-08', 140);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (249, 'Jackie', 'Rockwill', 'Marketing Manager', '2025-05-01', 252);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (250, 'Dolorita', 'Lowmass', 'Nurse', '2025-12-15', 99);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (251, 'Clarine', 'Rowthorne', 'Account Representative IV', '2025-07-11', 211);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (252, 'Adela', 'Attride', 'Office Assistant IV', '2025-09-01', 25);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (253, 'Ilka', 'Deverock', 'Occupational Therapist', '2025-09-29', 87);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (254, 'Orly', 'Drabble', 'Tax Accountant', '2026-01-05', 300);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (255, 'Ruy', 'Mullins', 'Operator', '2025-07-26', 312);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (256, 'Alasteir', 'Kunz', 'Developer IV', '2025-11-11', 415);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (257, 'Lon', 'Netting', 'Assistant Professor', '2025-10-22', 364);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (258, 'Esme', 'Good', 'Project Manager', '2025-07-25', 121);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (259, 'Felita', 'Stobbie', 'Computer Systems Analyst I', '2026-03-17', 297);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (260, 'Harrie', 'Mountstephen', 'Marketing Manager', '2025-12-18', 29);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (261, 'Flinn', 'Bogeys', 'Editor', '2025-08-21', 216);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (262, 'Nickey', 'Soars', 'Internal Auditor', '2026-02-01', 299);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (263, 'Laurie', 'Longrigg', 'Administrative Officer', '2025-09-27', 348);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (264, 'Reginald', 'Ackermann', 'Media Manager II', '2026-01-29', 192);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (265, 'Gipsy', 'Huleatt', 'Assistant Professor', '2025-08-05', 113);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (266, 'Melvyn', 'Boyson', 'Safety Technician III', '2025-04-01', 100);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (267, 'Beltran', 'Yves', 'Help Desk Technician', '2025-11-04', 500);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (268, 'Shoshanna', 'Dearness', 'Product Engineer', '2025-12-12', 222);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (269, 'Felix', 'Clooney', 'Software Test Engineer I', '2025-10-28', 425);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (270, 'Sollie', 'Ianittello', 'Design Engineer', '2026-01-21', 131);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (271, 'Timmie', 'Cantrill', 'Developer III', '2025-05-18', 209);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (272, 'Linus', 'Fidgeon', 'Chief Design Engineer', '2025-10-16', 343);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (273, 'Norri', 'Filintsev', 'Accountant III', '2025-08-15', 455);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (274, 'Carney', 'Seear', 'Payment Adjustment Coordinator', '2025-11-20', 407);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (275, 'Aaren', 'Wolfit', 'Environmental Tech', '2026-02-28', 318);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (276, 'Nicol', 'Tissington', 'Nurse', '2026-01-13', 37);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (277, 'Loni', 'McCullock', 'Structural Engineer', '2025-10-19', 42);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (278, 'Evvy', 'Sexon', 'Electrical Engineer', '2025-11-19', 325);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (279, 'Jewelle', 'Clawson', 'VP Marketing', '2026-02-06', 121);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (280, 'Ursala', 'Jendrassik', 'Desktop Support Technician', '2026-02-28', 18);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (281, 'Kelsy', 'McMurraya', 'Marketing Manager', '2025-06-01', 331);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (282, 'Hall', 'Jevon', 'Technical Writer', '2025-04-20', 310);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (283, 'Mikol', 'Hughes', 'Food Chemist', '2025-04-22', 4);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (284, 'Dacy', 'Sudworth', 'Occupational Therapist', '2025-12-02', 199);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (285, 'Verla', 'Ianiello', 'Web Designer IV', '2025-10-11', 381);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (286, 'Mirabelle', 'Hayto', 'Actuary', '2025-05-18', 40);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (287, 'Jeth', 'Gianettini', 'Account Executive', '2025-06-20', 351);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (288, 'Jacques', 'Cowderoy', 'Assistant Manager', '2025-12-03', 368);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (289, 'Nonnah', 'Floweth', 'Administrative Officer', '2025-11-01', 147);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (290, 'Danice', 'Minney', 'Media Manager III', '2026-03-10', 58);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (291, 'Gordy', 'Blaise', 'Nurse', '2025-05-09', 357);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (292, 'Tannie', 'Mousley', 'Help Desk Technician', '2025-07-16', 117);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (293, 'Corilla', 'Laxton', 'Product Engineer', '2025-05-24', 440);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (294, 'Zechariah', 'Karlicek', 'Structural Analysis Engineer', '2025-05-25', 351);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (295, 'Wash', 'Vasilov', 'Account Coordinator', '2025-11-25', 299);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (296, 'Em', 'Drain', 'Help Desk Operator', '2025-05-06', 362);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (297, 'Carie', 'Langworthy', 'Structural Analysis Engineer', '2025-12-25', 13);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (298, 'Mehetabel', 'Van Leeuwen', 'Automation Specialist III', '2025-11-20', 51);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (299, 'Yancey', 'McGuckin', 'Compensation Analyst', '2025-04-15', 76);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (300, 'Payton', 'Conant', 'Technical Writer', '2025-09-03', 312);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (301, 'Lauryn', 'Tilbrook', 'Recruiting Manager', '2025-10-01', 165);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (302, 'Nicolle', 'Dutton', 'Senior Cost Accountant', '2026-02-18', 182);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (303, 'Jayme', 'Petegree', 'Nurse Practicioner', '2025-08-03', 430);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (304, 'Winston', 'McDirmid', 'Registered Nurse', '2025-12-15', 109);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (305, 'Hazel', 'Sanders', 'Marketing Assistant', '2025-06-04', 7);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (306, 'Evaleen', 'Janisson', 'Librarian', '2026-01-02', 457);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (307, 'Andrus', 'Philbin', 'Web Designer II', '2026-02-02', 81);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (308, 'Angel', 'Gunbie', 'Senior Sales Associate', '2025-04-26', 298);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (309, 'Krisha', 'Earle', 'GIS Technical Architect', '2025-06-08', 261);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (310, 'Lanny', 'Drable', 'Geological Engineer', '2025-07-02', 26);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (311, 'Lela', 'Thickins', 'Dental Hygienist', '2026-01-02', 448);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (312, 'Nigel', 'Markovic', 'Automation Specialist III', '2025-12-03', 358);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (313, 'Hailey', 'Litchfield', 'Statistician I', '2025-07-14', 388);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (314, 'Ximenes', 'Dimmock', 'Structural Engineer', '2025-09-01', 82);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (315, 'Vernon', 'Hazeley', 'Design Engineer', '2025-10-29', 273);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (316, 'Lorie', 'Buckett', 'Staff Scientist', '2026-02-22', 138);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (317, 'Darlene', 'Dryburgh', 'General Manager', '2026-02-04', 126);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (318, 'Sayers', 'Douris', 'Graphic Designer', '2025-07-24', 483);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (319, 'Larine', 'Fishpond', 'Assistant Media Planner', '2025-09-11', 463);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (320, 'Lexine', 'Threadgould', 'Biostatistician III', '2025-07-08', 144);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (321, 'Marten', 'Issakov', 'VP Quality Control', '2025-10-08', 129);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (322, 'Esther', 'Kochs', 'Senior Financial Analyst', '2025-05-18', 469);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (323, 'Reg', 'Winton', 'Senior Cost Accountant', '2026-03-04', 335);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (324, 'Correy', 'Tocque', 'Environmental Specialist', '2025-10-09', 317);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (325, 'Berkeley', 'Greed', 'Recruiter', '2025-07-26', 137);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (326, 'Horatia', 'Briamo', 'Information Systems Manager', '2026-01-05', 474);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (327, 'Abigale', 'Shellsheere', 'Assistant Media Planner', '2025-09-28', 271);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (328, 'Adolphus', 'Sowerbutts', 'Actuary', '2025-05-08', 92);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (329, 'Mohandis', 'Postance', 'Web Designer II', '2025-05-22', 114);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (330, 'Arlyne', 'Ambler', 'Technical Writer', '2025-11-14', 424);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (331, 'Diane', 'Pauncefoot', 'Payment Adjustment Coordinator', '2025-12-24', 342);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (332, 'Jacquie', 'Chezelle', 'Human Resources Manager', '2026-01-06', 51);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (333, 'Akim', 'Van den Oord', 'Assistant Media Planner', '2026-02-18', 400);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (334, 'Paddie', 'Shelvey', 'VP Quality Control', '2025-05-30', 139);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (335, 'Eolanda', 'Goodyer', 'Sales Representative', '2025-12-03', 119);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (336, 'Krysta', 'Gabbitas', 'Structural Analysis Engineer', '2026-03-16', 191);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (337, 'Lenna', 'Garrity', 'VP Quality Control', '2025-04-30', 384);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (338, 'Isidora', 'Aldus', 'Quality Control Specialist', '2025-10-23', 298);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (339, 'Viv', 'McCullouch', 'Research Nurse', '2026-01-03', 157);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (340, 'Genvieve', 'Barby', 'Operator', '2026-01-24', 234);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (341, 'Krissie', 'Di Antonio', 'Compensation Analyst', '2025-12-31', 41);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (342, 'Bald', 'Fawthorpe', 'Technical Writer', '2025-05-24', 191);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (343, 'Caspar', 'Deek', 'Biostatistician II', '2025-12-10', 359);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (344, 'Anderea', 'Helgass', 'Nurse Practicioner', '2025-11-01', 495);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (345, 'Rocky', 'Stormonth', 'Web Designer II', '2026-02-02', 60);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (346, 'Matilda', 'Menat', 'Editor', '2026-01-30', 251);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (347, 'Kayley', 'Jerzak', 'Teacher', '2025-12-22', 254);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (348, 'Tyne', 'Spellissy', 'Environmental Specialist', '2025-07-30', 166);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (349, 'Vittorio', 'Lenney', 'Analyst Programmer', '2026-03-09', 231);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (350, 'Lanie', 'Rosenschein', 'Analog Circuit Design manager', '2025-12-23', 14);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (351, 'Irvine', 'Rossin', 'Speech Pathologist', '2025-04-05', 460);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (352, 'Alyssa', 'Rheubottom', 'Information Systems Manager', '2026-01-23', 53);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (353, 'Dasha', 'McCuaig', 'Senior Editor', '2025-09-29', 240);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (354, 'Nathan', 'Reville', 'Operator', '2025-07-11', 262);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (355, 'Eziechiele', 'O''Tierney', 'Account Representative IV', '2025-12-25', 148);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (356, 'Drew', 'Brobak', 'Assistant Professor', '2025-12-19', 202);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (357, 'Palm', 'Shobrook', 'Design Engineer', '2025-07-17', 450);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (358, 'Xenia', 'Ditter', 'Design Engineer', '2026-01-22', 436);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (359, 'Jemimah', 'Folds', 'Geological Engineer', '2026-01-21', 319);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (360, 'Thorsten', 'Scoon', 'Occupational Therapist', '2025-11-05', 196);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (361, 'Boothe', 'Longstaff', 'Account Representative II', '2026-03-04', 38);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (362, 'Lilllie', 'Keeves', 'Automation Specialist II', '2025-08-20', 327);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (363, 'Huntlee', 'Clinkard', 'Junior Executive', '2025-08-02', 42);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (364, 'Teddi', 'Tureville', 'Sales Representative', '2025-10-24', 15);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (365, 'Nollie', 'McGroarty', 'Nurse', '2025-10-30', 147);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (366, 'Gaby', 'Jado', 'GIS Technical Architect', '2025-04-16', 140);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (367, 'Elmo', 'Gimblett', 'Staff Accountant I', '2026-02-21', 208);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (368, 'Leeann', 'Weadick', 'Project Manager', '2026-01-17', 168);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (369, 'Humfrey', 'Munnion', 'Mechanical Systems Engineer', '2025-08-16', 81);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (370, 'Gideon', 'Tison', 'Senior Cost Accountant', '2026-03-02', 213);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (371, 'Larina', 'Tilzey', 'Operator', '2025-04-17', 4);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (372, 'Tasha', 'D''Andrea', 'Associate Professor', '2025-07-30', 368);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (373, 'Sheridan', 'Hebblewhite', 'Programmer I', '2025-10-01', 367);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (374, 'Fredrika', 'Fendley', 'Data Coordinator', '2025-11-16', 478);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (375, 'D''arcy', 'Hamshar', 'General Manager', '2025-04-10', 148);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (376, 'Cathryn', 'Kirvin', 'Teacher', '2025-05-28', 66);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (377, 'Inge', 'Bugge', 'Analyst Programmer', '2025-09-01', 238);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (378, 'Gerrard', 'Fairbard', 'Operator', '2025-12-16', 184);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (379, 'Vera', 'Millgate', 'Business Systems Development Analyst', '2025-09-14', 263);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (380, 'Marjy', 'Luna', 'Design Engineer', '2025-03-27', 223);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (381, 'Zelda', 'Filipputti', 'VP Product Management', '2025-06-30', 474);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (382, 'Lorri', 'Caldaro', 'Senior Developer', '2025-07-16', 94);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (383, 'Inge', 'Scutter', 'Legal Assistant', '2025-03-24', 182);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (384, 'Gannie', 'Vondrys', 'Senior Developer', '2026-01-24', 476);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (385, 'Gilburt', 'De Hooge', 'Geological Engineer', '2026-01-14', 75);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (386, 'Morley', 'Sancho', 'Information Systems Manager', '2025-07-31', 341);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (387, 'Kerstin', 'Pidgley', 'Technical Writer', '2025-06-26', 210);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (388, 'Mala', 'Tomczynski', 'Financial Advisor', '2025-12-19', 39);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (389, 'Nil', 'Poznanski', 'Software Engineer I', '2025-12-08', 345);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (390, 'Nicholle', 'Hopfner', 'Community Outreach Specialist', '2025-08-24', 334);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (391, 'Jarret', 'Pentony', 'Analyst Programmer', '2025-05-18', 405);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (392, 'Leanna', 'Rawll', 'Accountant II', '2026-03-10', 399);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (393, 'Berna', 'Scothorn', 'General Manager', '2025-03-20', 411);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (394, 'Wilie', 'Sitwell', 'Project Manager', '2025-08-16', 388);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (395, 'Far', 'Eddowis', 'Senior Cost Accountant', '2025-09-13', 301);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (396, 'Benito', 'Akam', 'Assistant Media Planner', '2025-07-08', 170);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (397, 'Shannon', 'Kelledy', 'Product Engineer', '2025-11-15', 472);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (398, 'Minda', 'Schouthede', 'Speech Pathologist', '2025-10-19', 386);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (399, 'Terence', 'St Pierre', 'Actuary', '2025-08-28', 249);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (400, 'Arvie', 'Davers', 'Librarian', '2025-03-31', 150);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (401, 'Linn', 'Mosedall', 'Senior Editor', '2026-02-06', 452);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (402, 'See', 'Stangoe', 'Systems Administrator I', '2025-04-11', 492);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (403, 'Tod', 'Cleeve', 'Chief Design Engineer', '2025-10-21', 97);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (404, 'Orland', 'Lingfoot', 'Automation Specialist IV', '2025-04-19', 176);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (405, 'Ange', 'Crottagh', 'Human Resources Assistant III', '2025-08-28', 488);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (406, 'Cheston', 'Willmetts', 'Sales Associate', '2025-04-10', 190);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (407, 'Orel', 'Blandamore', 'Statistician IV', '2025-11-17', 193);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (408, 'Osmond', 'Fellos', 'Help Desk Operator', '2025-08-09', 428);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (409, 'Petunia', 'Seemmonds', 'Nurse', '2026-02-22', 176);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (410, 'Gipsy', 'Exeter', 'Civil Engineer', '2025-12-13', 328);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (411, 'Itch', 'Grinyer', 'Desktop Support Technician', '2025-10-16', 136);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (412, 'Richie', 'Souster', 'Staff Accountant IV', '2026-03-17', 258);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (413, 'Crissy', 'Mc Mechan', 'Statistician III', '2025-05-21', 387);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (414, 'Melvin', 'Pearsey', 'Administrative Officer', '2025-07-10', 185);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (415, 'Jozef', 'Mingey', 'Analog Circuit Design manager', '2026-01-30', 196);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (416, 'Albert', 'Maass', 'Operator', '2025-08-01', 307);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (417, 'Puff', 'Beceril', 'Cost Accountant', '2025-11-17', 464);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (418, 'Hillyer', 'Yegorkov', 'Senior Sales Associate', '2025-11-13', 158);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (419, 'Wayland', 'Parry', 'Human Resources Manager', '2025-08-04', 92);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (420, 'Marley', 'Brogiotti', 'Pharmacist', '2026-03-07', 220);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (421, 'Georgine', 'Crosseland', 'Technical Writer', '2025-10-17', 234);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (422, 'Shelton', 'Prall', 'Software Test Engineer II', '2025-06-24', 91);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (423, 'Margery', 'Nezey', 'Marketing Assistant', '2025-08-31', 11);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (424, 'Kermit', 'Legate', 'Information Systems Manager', '2025-05-01', 195);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (425, 'Chauncey', 'Bycraft', 'Design Engineer', '2025-06-01', 346);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (426, 'Fabio', 'Kennerley', 'Senior Quality Engineer', '2026-01-31', 250);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (427, 'Justin', 'Niezen', 'Community Outreach Specialist', '2025-06-16', 159);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (428, 'Viviyan', 'Campanelli', 'Data Coordinator', '2025-09-27', 334);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (429, 'Northrup', 'Mallison', 'Quality Control Specialist', '2025-11-15', 306);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (430, 'Filmer', 'Kelledy', 'Product Engineer', '2026-02-28', 329);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (431, 'Way', 'Quig', 'Tax Accountant', '2025-06-22', 89);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (432, 'Angelique', 'McGaughay', 'Graphic Designer', '2025-07-07', 45);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (433, 'Marchall', 'Vellden', 'Cost Accountant', '2025-04-15', 198);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (434, 'Leonanie', 'Fairbank', 'Accounting Assistant III', '2025-12-26', 359);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (435, 'Benita', 'Paskerful', 'Food Chemist', '2026-01-13', 273);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (436, 'Gerianne', 'Corless', 'Web Designer IV', '2025-05-18', 204);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (437, 'Dorine', 'Woollard', 'Human Resources Assistant III', '2025-08-10', 346);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (438, 'Aloisia', 'Grono', 'Senior Financial Analyst', '2025-08-07', 67);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (439, 'Layla', 'Guiduzzi', 'Quality Engineer', '2025-07-05', 19);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (440, 'Cathrine', 'Jolliss', 'VP Accounting', '2025-07-27', 131);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (441, 'Alyda', 'Nacey', 'VP Marketing', '2025-11-18', 485);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (442, 'Bethena', 'Dallan', 'Sales Representative', '2025-05-17', 286);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (443, 'Jilli', 'Stanyer', 'Geologist I', '2026-03-07', 457);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (444, 'Adolphus', 'Sherrin', 'VP Product Management', '2025-10-23', 350);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (445, 'Robbie', 'Frangleton', 'Director of Sales', '2026-02-15', 180);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (446, 'Anselma', 'Mackriell', 'Analyst Programmer', '2025-04-02', 82);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (447, 'Hali', 'Kenningham', 'Nuclear Power Engineer', '2025-05-06', 167);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (448, 'Reggie', 'Leven', 'Safety Technician IV', '2025-12-20', 186);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (449, 'Blondelle', 'Dispencer', 'Nurse Practicioner', '2025-07-03', 294);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (450, 'Alphonso', 'Blenkiron', 'Technical Writer', '2025-08-09', 268);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (451, 'Karly', 'Sichardt', 'Programmer IV', '2026-02-28', 463);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (452, 'Lazar', 'Sondon', 'Desktop Support Technician', '2025-11-10', 83);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (453, 'Claribel', 'Beall', 'Professor', '2025-12-03', 56);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (454, 'Emilee', 'Tennant', 'Speech Pathologist', '2026-01-01', 260);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (455, 'Maggee', 'Cutten', 'Cost Accountant', '2025-12-15', 4);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (456, 'Sheilakathryn', 'Foynes', 'Senior Cost Accountant', '2025-05-14', 10);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (457, 'Berri', 'MacShane', 'VP Marketing', '2025-03-27', 433);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (458, 'Herbie', 'Rawdall', 'Software Consultant', '2025-07-23', 288);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (459, 'Salvidor', 'Eltune', 'Systems Administrator II', '2025-10-30', 297);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (460, 'Carlin', 'Gallihaulk', 'Desktop Support Technician', '2025-09-27', 121);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (461, 'Carce', 'O''Calleran', 'Human Resources Manager', '2025-07-17', 191);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (462, 'Berny', 'Ilyuchyov', 'VP Sales', '2025-08-06', 147);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (463, 'Ericka', 'Pelzer', 'Senior Editor', '2025-08-17', 307);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (464, 'Pepito', 'Thackwray', 'Administrative Officer', '2026-01-06', 261);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (465, 'Bailie', 'Rodinger', 'Information Systems Manager', '2025-05-12', 12);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (466, 'Elisabetta', 'Gamble', 'Teacher', '2025-11-28', 430);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (467, 'Bobbette', 'Le Fevre', 'Actuary', '2025-09-06', 165);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (468, 'Murielle', 'Speer', 'Graphic Designer', '2025-05-14', 459);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (469, 'Kaine', 'Kidde', 'Quality Engineer', '2025-12-05', 258);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (470, 'Daphene', 'Raithby', 'Database Administrator IV', '2025-09-24', 73);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (471, 'Bennie', 'Farbrace', 'Environmental Tech', '2025-11-24', 122);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (472, 'Kimball', 'Alvarez', 'Social Worker', '2025-08-25', 228);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (473, 'Patsy', 'Rubrow', 'Business Systems Development Analyst', '2026-02-09', 272);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (474, 'Milly', 'Moorrud', 'Assistant Professor', '2025-08-24', 393);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (475, 'Putnam', 'Deighton', 'Staff Accountant IV', '2025-10-10', 249);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (476, 'Saundra', 'Beckenham', 'General Manager', '2025-07-27', 361);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (477, 'Georgina', 'Norker', 'Senior Sales Associate', '2025-12-27', 67);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (478, 'Yalonda', 'Gorghetto', 'Executive Secretary', '2025-08-24', 485);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (479, 'Harald', 'Manterfield', 'Environmental Tech', '2026-01-19', 75);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (480, 'Maurita', 'Dwelley', 'Senior Quality Engineer', '2025-12-14', 403);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (481, 'Aurie', 'Chadbourne', 'Operator', '2026-02-11', 461);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (482, 'Thoma', 'Sorro', 'Web Developer III', '2025-09-06', 382);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (483, 'Misty', 'Armsby', 'Editor', '2025-05-11', 107);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (484, 'Carolyn', 'Matthieson', 'Software Engineer I', '2025-04-26', 66);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (485, 'Anselm', 'Jenkin', 'Systems Administrator I', '2025-08-28', 215);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (486, 'Merrielle', 'Oret', 'Help Desk Operator', '2025-12-24', 407);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (487, 'Maryjo', 'Novakovic', 'Paralegal', '2025-07-09', 280);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (488, 'Rosalinde', 'Klein', 'Pharmacist', '2026-01-06', 18);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (489, 'Niall', 'Duckfield', 'Automation Specialist I', '2025-05-18', 181);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (490, 'Montague', 'Hibling', 'Environmental Specialist', '2025-09-24', 122);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (491, 'Arni', 'Ready', 'Registered Nurse', '2025-12-23', 150);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (492, 'Marieann', 'Finnimore', 'Analog Circuit Design manager', '2026-01-10', 130);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (493, 'Isac', 'Napleton', 'Account Representative II', '2025-07-31', 127);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (494, 'Merci', 'Wharin', 'Software Engineer II', '2025-07-02', 255);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (495, 'Etheline', 'Haensel', 'Registered Nurse', '2026-02-23', 189);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (496, 'Antonius', 'Novis', 'Software Consultant', '2025-06-10', 91);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (497, 'Lilas', 'Limmer', 'Legal Assistant', '2025-08-02', 62);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (498, 'Roseline', 'Mellhuish', 'Occupational Therapist', '2025-07-14', 128);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (499, 'Cyril', 'Fontenot', 'Software Engineer II', '2025-11-09', 84);
insert into EMPLOYEES (EmployeeID, FirstName, LastName, Role, HireDate, WarehouseID) values (500, 'June', 'Matusiak', 'Help Desk Technician', '2025-06-13', 302);
