insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (1, 4, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2025-08-19', 18, 286);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (2, 1, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-08-27', 311, 72);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (3, 5, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2025-04-16', 473, 361);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (4, 2, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2025-09-14', 363, 111);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (5, 5, 'Sed ante. Vivamus tortor.', '2025-05-16', 199, 392);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (6, 2, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2026-01-15', 77, 276);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (7, 5, 'Phasellus in felis.', '2026-03-02', 446, 421);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (8, 5, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2026-02-01', 126, 455);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (9, 3, 'Proin risus. Praesent lectus.', '2026-01-05', 347, 279);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (10, 1, 'Proin risus.', '2026-02-22', 218, 44);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (11, 2, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', '2025-12-15', 18, 399);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (12, 4, 'In congue.', '2025-05-05', 89, 57);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (13, 2, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2026-02-02', 302, 69);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (14, 3, 'Aliquam non mauris. Morbi non lectus.', '2025-08-28', 391, 372);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (15, 1, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2026-03-02', 353, 345);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (16, 2, 'Aenean lectus.', '2025-10-25', 496, 132);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (17, 2, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2026-03-16', 385, 87);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (18, 5, 'Nulla ut erat id mauris vulputate elementum.', '2025-09-28', 423, 97);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (19, 3, 'Sed ante. Vivamus tortor.', '2025-06-06', 87, 493);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (20, 1, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2025-04-18', 452, 466);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (21, 5, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2026-01-14', 495, 154);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (22, 5, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2025-10-18', 311, 326);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (23, 1, 'Nulla suscipit ligula in lacus.', '2025-03-20', 232, 381);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (24, 1, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2026-02-01', 335, 444);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (25, 3, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2025-12-23', 253, 363);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (26, 4, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2025-11-14', 303, 393);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (27, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2026-02-03', 390, 291);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (28, 4, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2025-09-03', 154, 272);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (29, 1, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2026-03-10', 261, 75);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (30, 3, 'Mauris sit amet eros.', '2025-12-15', 93, 319);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (31, 4, 'Morbi porttitor lorem id ligula.', '2025-05-21', 107, 190);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (32, 2, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2025-08-23', 445, 407);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (33, 3, 'Suspendisse potenti.', '2025-08-09', 226, 77);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (34, 5, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2026-02-18', 176, 384);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (35, 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2025-04-14', 306, 52);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (36, 4, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2025-06-19', 336, 340);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (37, 3, 'Suspendisse potenti.', '2025-10-13', 454, 216);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (38, 5, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2025-12-16', 13, 158);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (39, 2, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2025-05-24', 220, 500);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (40, 4, 'Suspendisse accumsan tortor quis turpis. Sed ante.', '2025-10-23', 240, 463);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (41, 4, 'Nullam sit amet turpis elementum ligula vehicula consequat.', '2025-08-19', 139, 23);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (42, 5, 'Aliquam quis turpis eget elit sodales scelerisque.', '2025-08-19', 342, 34);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (43, 3, 'Etiam justo.', '2025-08-12', 192, 381);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (44, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2026-02-15', 358, 361);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (45, 5, 'Cras non velit nec nisi vulputate nonummy.', '2025-08-31', 425, 407);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (46, 3, 'Nulla nisl.', '2025-03-23', 59, 337);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (47, 1, 'Morbi a ipsum. Integer a nibh.', '2025-03-24', 464, 455);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (48, 2, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2025-11-09', 107, 3);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (49, 1, 'Integer non velit.', '2025-09-03', 187, 418);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (50, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2025-12-23', 344, 258);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (51, 4, 'Proin risus.', '2025-11-17', 112, 1);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (52, 4, 'Etiam faucibus cursus urna.', '2025-11-23', 428, 36);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (53, 2, 'Phasellus id sapien in sapien iaculis congue.', '2025-05-29', 341, 151);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (54, 1, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2025-09-26', 399, 334);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (55, 5, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2025-09-21', 329, 3);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (56, 1, 'Integer ac neque. Duis bibendum.', '2025-09-18', 394, 378);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (57, 3, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2025-07-01', 104, 111);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (58, 1, 'Morbi ut odio.', '2025-06-18', 117, 324);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (59, 2, 'Proin at turpis a pede posuere nonummy. Integer non velit.', '2026-01-25', 71, 68);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (60, 2, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2026-01-04', 119, 460);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (61, 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2025-12-09', 260, 417);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (62, 1, 'Duis consequat dui nec nisi volutpat eleifend.', '2025-03-19', 162, 217);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (63, 1, 'In blandit ultrices enim.', '2025-04-03', 309, 193);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (64, 3, 'Nunc rhoncus dui vel sem.', '2025-10-22', 468, 113);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (65, 2, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2026-01-17', 404, 378);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (66, 3, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2025-07-11', 158, 487);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (67, 1, 'Nullam molestie nibh in lectus.', '2025-10-22', 212, 194);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (68, 4, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2025-06-12', 55, 142);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (69, 5, 'Duis aliquam convallis nunc.', '2025-06-05', 268, 135);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (70, 3, 'Morbi vel lectus in quam fringilla rhoncus.', '2025-06-11', 277, 20);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (71, 3, 'Nunc purus.', '2025-08-31', 53, 378);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (72, 3, 'Nullam porttitor lacus at turpis.', '2026-02-14', 383, 469);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (73, 2, 'Nulla mollis molestie lorem. Quisque ut erat.', '2026-02-19', 147, 154);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (74, 1, 'Nullam molestie nibh in lectus. Pellentesque at nulla.', '2025-04-30', 405, 331);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (75, 4, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2025-04-04', 282, 296);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (76, 2, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2026-02-21', 453, 355);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (77, 2, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '2025-04-17', 271, 438);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (78, 3, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2025-08-03', 48, 487);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (79, 4, 'Sed accumsan felis.', '2025-08-11', 353, 260);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (80, 3, 'In sagittis dui vel nisl.', '2025-04-30', 448, 297);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (81, 4, 'Duis consequat dui nec nisi volutpat eleifend.', '2025-07-23', 213, 396);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (82, 5, 'Morbi a ipsum.', '2026-02-16', 123, 479);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (83, 2, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2025-12-05', 32, 83);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (84, 1, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '2025-03-19', 230, 44);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (85, 2, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2025-08-20', 183, 439);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (86, 3, 'Phasellus in felis. Donec semper sapien a libero.', '2025-12-23', 22, 406);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (87, 4, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2026-01-15', 132, 108);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (88, 4, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', '2025-12-20', 79, 398);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (89, 3, 'Nullam porttitor lacus at turpis.', '2025-11-25', 248, 145);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (90, 4, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2025-09-09', 198, 171);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (91, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-04-08', 447, 469);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (92, 4, 'Ut tellus.', '2025-06-03', 464, 86);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (93, 2, 'Nulla tempus.', '2026-03-12', 85, 129);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (94, 5, 'Praesent blandit.', '2025-09-26', 10, 178);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (95, 3, 'Maecenas ut massa quis augue luctus tincidunt.', '2025-07-04', 296, 185);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (96, 4, 'Cras in purus eu magna vulputate luctus.', '2025-08-19', 233, 369);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (97, 3, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2025-10-05', 449, 313);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (98, 4, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2026-02-24', 175, 278);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (99, 3, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2025-04-26', 71, 86);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (100, 1, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2025-07-02', 86, 233);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (101, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-06-28', 452, 304);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (102, 1, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2025-06-16', 422, 317);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (103, 5, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2025-11-27', 98, 54);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (104, 3, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2025-10-15', 452, 476);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (105, 5, 'Aliquam erat volutpat.', '2025-11-02', 483, 474);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (106, 1, 'Morbi a ipsum.', '2025-09-22', 254, 436);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (107, 5, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2025-09-27', 19, 71);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (108, 4, 'In hac habitasse platea dictumst.', '2025-07-31', 125, 397);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (109, 5, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2025-07-27', 451, 266);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (110, 1, 'Quisque ut erat.', '2025-08-02', 277, 448);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (111, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2025-08-07', 293, 46);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (112, 5, 'Sed ante. Vivamus tortor.', '2026-03-13', 356, 140);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (113, 1, 'Aenean lectus. Pellentesque eget nunc.', '2026-01-10', 304, 324);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (114, 2, 'In hac habitasse platea dictumst.', '2025-08-02', 13, 342);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (115, 5, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2025-08-30', 11, 101);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (116, 5, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '2025-04-22', 337, 487);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (117, 5, 'Duis at velit eu est congue elementum.', '2026-03-17', 486, 353);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (118, 2, 'Vivamus tortor. Duis mattis egestas metus.', '2025-08-05', 248, 318);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (119, 4, 'Morbi quis tortor id nulla ultrices aliquet.', '2025-09-10', 82, 449);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (120, 5, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2026-02-14', 84, 408);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (121, 4, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '2025-09-26', 186, 216);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (122, 1, 'Fusce consequat. Nulla nisl.', '2025-05-07', 37, 56);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (123, 5, 'Duis ac nibh.', '2025-04-06', 399, 138);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (124, 1, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2025-04-19', 25, 3);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (125, 5, 'Ut tellus.', '2025-06-23', 71, 17);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (126, 5, 'Aenean lectus. Pellentesque eget nunc.', '2025-05-14', 405, 291);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (127, 3, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2025-03-28', 404, 318);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (128, 2, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', '2025-07-13', 341, 248);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (129, 1, 'Nunc nisl.', '2025-05-20', 368, 332);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (130, 2, 'Aenean auctor gravida sem.', '2025-04-10', 81, 162);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (131, 1, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2025-10-11', 485, 120);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (132, 3, 'In congue. Etiam justo.', '2025-04-01', 479, 367);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (133, 2, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', '2026-02-12', 284, 194);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (134, 5, 'Mauris ullamcorper purus sit amet nulla.', '2025-03-28', 242, 336);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (135, 4, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2025-08-10', 266, 267);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (136, 2, 'Donec ut dolor.', '2026-03-10', 450, 156);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (137, 2, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2025-03-20', 186, 490);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (138, 1, 'In congue. Etiam justo.', '2025-08-27', 365, 142);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (139, 3, 'Pellentesque ultrices mattis odio.', '2026-02-15', 330, 267);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (140, 4, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2025-04-03', 415, 243);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (141, 2, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2025-11-19', 376, 213);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (142, 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2025-04-09', 417, 92);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (143, 5, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2025-12-23', 407, 355);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (144, 4, 'Integer non velit.', '2025-05-11', 40, 216);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (145, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2025-10-31', 401, 292);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (146, 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2025-07-13', 204, 452);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (147, 2, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '2025-05-29', 286, 400);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (148, 1, 'Cras pellentesque volutpat dui.', '2025-12-23', 197, 480);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (149, 5, 'Nullam varius. Nulla facilisi.', '2025-10-24', 135, 205);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (150, 1, 'Nam dui.', '2025-07-22', 251, 42);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (151, 4, 'Cras non velit nec nisi vulputate nonummy.', '2026-03-10', 315, 374);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (152, 5, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2025-07-08', 208, 4);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (153, 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', '2025-11-29', 287, 223);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (154, 3, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '2025-06-10', 400, 132);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (155, 3, 'Morbi porttitor lorem id ligula.', '2025-05-25', 442, 307);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (156, 2, 'Phasellus sit amet erat. Nulla tempus.', '2025-10-10', 486, 62);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (157, 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '2025-12-19', 353, 257);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (158, 2, 'Proin risus.', '2025-08-09', 480, 210);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (159, 4, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2025-07-03', 247, 293);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (160, 4, 'Quisque ut erat. Curabitur gravida nisi at nibh.', '2025-12-01', 108, 417);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (161, 5, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2025-03-22', 91, 244);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (162, 4, 'Quisque ut erat.', '2026-01-17', 250, 7);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (163, 5, 'Nulla ac enim.', '2026-02-08', 483, 18);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (164, 3, 'Duis mattis egestas metus. Aenean fermentum.', '2025-08-21', 481, 12);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (165, 1, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2025-10-08', 53, 475);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (166, 1, 'Aenean fermentum.', '2025-11-13', 280, 485);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (167, 3, 'Vestibulum rutrum rutrum neque.', '2025-06-03', 182, 371);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (168, 5, 'Nulla justo.', '2025-04-29', 164, 480);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (169, 4, 'In hac habitasse platea dictumst.', '2025-12-04', 334, 273);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (170, 4, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2025-08-30', 161, 476);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (171, 5, 'Suspendisse ornare consequat lectus.', '2025-04-28', 239, 172);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (172, 1, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2025-06-09', 201, 243);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (173, 1, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2026-03-08', 228, 319);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (174, 4, 'Donec semper sapien a libero. Nam dui.', '2026-01-13', 91, 274);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (175, 1, 'Nam dui.', '2025-11-10', 373, 354);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (176, 4, 'Etiam justo. Etiam pretium iaculis justo.', '2025-08-12', 253, 10);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (177, 4, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2025-12-14', 24, 479);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (178, 4, 'Nunc purus. Phasellus in felis.', '2025-03-27', 42, 399);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (179, 5, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2025-07-03', 318, 415);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (180, 3, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2025-04-21', 70, 94);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (181, 5, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2025-07-20', 169, 215);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (182, 2, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2025-09-14', 153, 255);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (183, 1, 'Duis at velit eu est congue elementum.', '2025-06-07', 63, 167);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (184, 3, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2026-01-04', 283, 239);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (185, 2, 'Donec semper sapien a libero.', '2026-03-12', 415, 98);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (186, 3, 'Vivamus tortor. Duis mattis egestas metus.', '2025-06-17', 303, 170);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (187, 4, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2025-10-21', 256, 65);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (188, 3, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2026-01-26', 432, 408);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (189, 4, 'Nulla tellus. In sagittis dui vel nisl.', '2025-07-05', 490, 226);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (190, 5, 'Praesent blandit.', '2025-10-20', 361, 159);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (191, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2025-09-05', 34, 80);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (192, 5, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2026-03-17', 213, 3);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (193, 4, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2026-01-11', 392, 351);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (194, 2, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2025-04-05', 155, 167);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (195, 3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2025-12-18', 468, 48);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (196, 2, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2025-10-25', 258, 299);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (197, 3, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '2025-07-27', 392, 110);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (198, 4, 'Aenean sit amet justo.', '2026-02-12', 312, 148);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (199, 3, 'Nulla tempus.', '2025-09-20', 9, 271);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (200, 3, 'Fusce consequat.', '2025-04-12', 426, 438);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (201, 3, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2025-06-11', 105, 409);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (202, 3, 'Phasellus in felis.', '2025-03-28', 242, 432);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (203, 5, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2026-02-28', 86, 149);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (204, 3, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2025-08-25', 10, 342);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (205, 4, 'Praesent id massa id nisl venenatis lacinia.', '2026-01-14', 213, 161);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (206, 4, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2025-05-15', 448, 55);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (207, 4, 'Nulla suscipit ligula in lacus.', '2025-04-13', 254, 366);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (208, 1, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '2025-07-03', 438, 234);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (209, 5, 'In eleifend quam a odio. In hac habitasse platea dictumst.', '2025-10-11', 79, 486);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (210, 1, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2025-11-17', 98, 187);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (211, 3, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2025-08-02', 385, 97);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (212, 1, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2026-03-12', 26, 145);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (213, 1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '2026-03-08', 168, 1);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (214, 2, 'Nulla tempus.', '2025-06-10', 324, 460);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (215, 1, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2025-08-19', 380, 293);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (216, 1, 'Nulla justo.', '2025-08-13', 17, 345);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (217, 4, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2025-11-12', 232, 179);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (218, 4, 'In congue. Etiam justo.', '2025-04-19', 38, 198);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (219, 4, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2026-01-11', 388, 288);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (220, 2, 'Aenean sit amet justo.', '2025-08-21', 496, 246);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (221, 1, 'Vestibulum sed magna at nunc commodo placerat.', '2025-10-17', 159, 409);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (222, 1, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2025-11-09', 178, 342);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (223, 5, 'Donec vitae nisi.', '2025-11-19', 437, 413);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (224, 3, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2025-04-14', 488, 254);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (225, 4, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2026-03-10', 398, 444);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (226, 3, 'Morbi porttitor lorem id ligula.', '2025-06-15', 249, 41);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (227, 2, 'Etiam pretium iaculis justo.', '2025-09-13', 209, 151);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (228, 5, 'Donec ut dolor.', '2025-10-30', 385, 101);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (229, 4, 'Phasellus id sapien in sapien iaculis congue.', '2025-11-19', 444, 472);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (230, 2, 'Integer a nibh. In quis justo.', '2025-09-02', 142, 108);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (231, 4, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2025-10-19', 492, 96);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (232, 2, 'Vestibulum rutrum rutrum neque.', '2025-12-10', 448, 474);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (233, 5, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2025-04-20', 282, 165);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (234, 4, 'Vestibulum sed magna at nunc commodo placerat.', '2025-10-02', 214, 189);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (235, 3, 'Cras non velit nec nisi vulputate nonummy.', '2025-04-26', 204, 191);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (236, 5, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2026-02-27', 168, 325);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (237, 5, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2025-07-23', 328, 130);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (238, 3, 'Vivamus vestibulum sagittis sapien.', '2025-10-06', 37, 173);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (239, 5, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2025-09-11', 470, 494);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (240, 4, 'Suspendisse potenti. In eleifend quam a odio.', '2025-05-02', 145, 500);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (241, 4, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2025-06-02', 80, 445);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (242, 3, 'Proin risus. Praesent lectus.', '2025-07-28', 10, 14);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (243, 3, 'Suspendisse accumsan tortor quis turpis.', '2026-02-19', 311, 158);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (244, 1, 'Donec dapibus.', '2025-08-27', 222, 350);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (245, 3, 'In hac habitasse platea dictumst.', '2026-02-19', 59, 143);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (246, 5, 'Suspendisse accumsan tortor quis turpis.', '2026-01-16', 105, 219);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (247, 2, 'In sagittis dui vel nisl. Duis ac nibh.', '2025-04-26', 301, 73);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (248, 5, 'Donec semper sapien a libero.', '2025-04-23', 79, 249);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (249, 5, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2026-03-14', 401, 371);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (250, 3, 'Ut tellus.', '2025-05-27', 329, 354);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (251, 2, 'Nulla nisl.', '2025-11-21', 161, 366);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (252, 5, 'Etiam faucibus cursus urna.', '2025-05-27', 120, 14);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (253, 3, 'In quis justo. Maecenas rhoncus aliquam lacus.', '2025-10-20', 369, 230);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (254, 3, 'Maecenas tincidunt lacus at velit.', '2025-04-16', 472, 427);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (255, 2, 'Nulla tempus.', '2025-06-01', 187, 471);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (256, 2, 'Nullam molestie nibh in lectus. Pellentesque at nulla.', '2025-11-28', 79, 61);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (257, 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2026-03-09', 184, 368);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (258, 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2025-08-17', 161, 79);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (259, 3, 'Nulla tempus.', '2025-10-02', 376, 39);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (260, 2, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2026-03-01', 468, 233);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (261, 2, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-11-16', 364, 307);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (262, 3, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2025-09-04', 285, 110);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (263, 3, 'In eleifend quam a odio.', '2025-08-25', 23, 161);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (264, 4, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '2026-02-26', 64, 233);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (265, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2025-12-02', 344, 44);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (266, 2, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2025-03-22', 463, 87);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (267, 2, 'Sed accumsan felis.', '2025-07-26', 171, 375);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (268, 3, 'Mauris lacinia sapien quis libero.', '2025-08-23', 239, 262);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (269, 2, 'In eleifend quam a odio. In hac habitasse platea dictumst.', '2025-12-01', 259, 370);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (270, 5, 'Donec dapibus. Duis at velit eu est congue elementum.', '2025-05-26', 417, 140);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (271, 2, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2025-08-14', 224, 236);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (272, 3, 'Nullam molestie nibh in lectus.', '2025-07-28', 70, 341);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (273, 1, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2025-05-25', 211, 267);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (274, 3, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '2025-09-12', 21, 386);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (275, 1, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2025-09-11', 30, 431);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (276, 2, 'Proin interdum mauris non ligula pellentesque ultrices.', '2026-01-26', 366, 252);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (277, 5, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '2025-05-27', 164, 495);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (278, 3, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-07-27', 497, 423);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (279, 2, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', '2026-02-02', 91, 72);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (280, 4, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', '2025-10-26', 130, 26);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (281, 1, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2026-01-01', 30, 110);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (282, 2, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2026-02-19', 78, 139);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (283, 5, 'Integer tincidunt ante vel ipsum.', '2025-12-23', 172, 115);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (284, 1, 'Aenean sit amet justo.', '2026-02-10', 354, 334);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (285, 4, 'In congue. Etiam justo.', '2025-09-20', 495, 63);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (286, 2, 'Phasellus in felis.', '2025-03-27', 425, 442);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (287, 1, 'Nulla suscipit ligula in lacus.', '2025-08-23', 366, 120);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (288, 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '2025-07-05', 424, 455);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (289, 2, 'In hac habitasse platea dictumst.', '2025-08-29', 205, 481);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (290, 5, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2025-09-20', 149, 394);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (291, 4, 'Nulla ac enim.', '2025-04-28', 197, 52);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (292, 5, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', '2025-10-23', 385, 409);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (293, 1, 'Duis mattis egestas metus.', '2025-05-19', 324, 113);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (294, 5, 'Praesent blandit. Nam nulla.', '2025-09-19', 322, 481);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (295, 1, 'Nulla nisl.', '2025-10-09', 80, 271);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (296, 4, 'Fusce consequat.', '2025-07-01', 145, 384);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (297, 3, 'Nulla ac enim.', '2025-11-27', 409, 440);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (298, 4, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2025-10-23', 393, 423);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (299, 5, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-10-24', 380, 87);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (300, 1, 'Praesent blandit.', '2025-05-08', 140, 460);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (301, 4, 'Donec semper sapien a libero.', '2025-10-10', 487, 182);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (302, 2, 'Nulla nisl.', '2025-08-05', 71, 162);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (303, 3, 'Donec posuere metus vitae ipsum.', '2025-12-11', 221, 6);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (304, 1, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2025-04-11', 415, 397);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (305, 2, 'Curabitur at ipsum ac tellus semper interdum.', '2026-01-10', 60, 258);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (306, 5, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2026-02-19', 472, 347);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (307, 5, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2025-06-13', 286, 140);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (308, 3, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2025-10-28', 258, 454);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (309, 5, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2025-04-16', 238, 263);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (310, 1, 'Morbi non quam nec dui luctus rutrum.', '2025-04-25', 266, 434);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (311, 1, 'Vestibulum ac est lacinia nisi venenatis tristique.', '2025-08-22', 17, 214);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (312, 4, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2025-05-20', 101, 83);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (313, 2, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2025-07-11', 246, 317);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (314, 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2026-02-21', 174, 450);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (315, 3, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2025-06-14', 462, 440);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (316, 3, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2026-03-09', 469, 400);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (317, 2, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2025-09-22', 146, 8);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (318, 2, 'In blandit ultrices enim.', '2026-03-09', 347, 79);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (319, 3, 'Donec dapibus.', '2025-04-28', 307, 439);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (320, 1, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2025-05-26', 239, 290);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (321, 1, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2025-08-03', 438, 176);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (322, 5, 'Mauris lacinia sapien quis libero.', '2025-07-23', 472, 9);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (323, 5, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2025-10-14', 342, 32);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (324, 4, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2026-02-14', 454, 70);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (325, 4, 'Nullam porttitor lacus at turpis.', '2025-10-14', 40, 23);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (326, 3, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2025-09-12', 385, 10);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (327, 3, 'Donec semper sapien a libero.', '2026-03-14', 470, 143);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (328, 3, 'Proin at turpis a pede posuere nonummy.', '2025-08-21', 35, 323);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (329, 3, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2025-04-06', 491, 463);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (330, 5, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2025-07-12', 45, 69);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (331, 3, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2025-03-30', 40, 63);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (332, 4, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2025-06-12', 143, 299);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (333, 3, 'Nulla suscipit ligula in lacus.', '2025-12-08', 493, 365);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (334, 5, 'Vestibulum ac est lacinia nisi venenatis tristique.', '2025-11-02', 202, 263);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (335, 2, 'Nulla nisl. Nunc nisl.', '2025-10-04', 154, 336);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (336, 1, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', '2025-04-21', 264, 25);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (337, 4, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2025-11-22', 447, 305);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (338, 5, 'Vestibulum sed magna at nunc commodo placerat.', '2025-08-15', 462, 112);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (339, 1, 'Cras in purus eu magna vulputate luctus.', '2025-08-26', 28, 34);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (340, 4, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2026-03-10', 141, 337);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (341, 3, 'Fusce consequat.', '2025-04-21', 201, 422);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (342, 1, 'Nullam porttitor lacus at turpis.', '2025-12-01', 442, 470);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (343, 2, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2026-02-11', 354, 154);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (344, 1, 'Phasellus sit amet erat.', '2026-01-13', 91, 145);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (345, 2, 'Mauris ullamcorper purus sit amet nulla.', '2026-02-14', 421, 271);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (346, 4, 'Cras in purus eu magna vulputate luctus.', '2025-12-17', 190, 184);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (347, 1, 'Donec dapibus.', '2025-09-06', 129, 371);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (348, 4, 'Nulla mollis molestie lorem. Quisque ut erat.', '2025-10-09', 79, 252);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (349, 4, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2026-01-09', 188, 158);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (350, 4, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2025-09-25', 234, 465);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (351, 2, 'Phasellus id sapien in sapien iaculis congue.', '2026-03-15', 50, 268);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (352, 1, 'Etiam faucibus cursus urna.', '2026-03-13', 231, 103);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (353, 4, 'Morbi porttitor lorem id ligula.', '2025-08-28', 278, 236);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (354, 1, 'In hac habitasse platea dictumst.', '2026-02-22', 331, 484);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (355, 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2025-04-07', 296, 103);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (356, 3, 'Suspendisse potenti. Nullam porttitor lacus at turpis.', '2025-04-01', 217, 355);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (357, 1, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2025-05-14', 267, 162);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (358, 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2025-12-23', 157, 365);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (359, 2, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2025-08-01', 187, 106);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (360, 4, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '2025-03-28', 77, 134);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (361, 4, 'Vestibulum rutrum rutrum neque.', '2025-09-13', 403, 74);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (362, 4, 'Integer ac leo. Pellentesque ultrices mattis odio.', '2025-09-14', 416, 216);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (363, 3, 'Pellentesque ultrices mattis odio.', '2025-07-13', 368, 424);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (364, 1, 'Donec quis orci eget orci vehicula condimentum.', '2025-04-14', 479, 379);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (365, 5, 'Suspendisse potenti. In eleifend quam a odio.', '2025-11-10', 125, 444);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (366, 4, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '2025-06-11', 228, 286);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (367, 2, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2025-07-04', 158, 276);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (368, 4, 'Cras in purus eu magna vulputate luctus.', '2026-03-01', 99, 393);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (369, 5, 'Donec ut mauris eget massa tempor convallis.', '2026-02-19', 286, 233);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (370, 1, 'Duis at velit eu est congue elementum.', '2026-02-27', 443, 67);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (371, 5, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2025-07-17', 209, 492);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (372, 3, 'Aenean sit amet justo.', '2025-06-11', 446, 467);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (373, 5, 'Nulla tellus. In sagittis dui vel nisl.', '2026-02-13', 477, 41);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (374, 1, 'Pellentesque at nulla.', '2025-03-31', 367, 205);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (375, 1, 'Proin interdum mauris non ligula pellentesque ultrices.', '2026-01-11', 486, 180);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (376, 3, 'Nunc purus. Phasellus in felis.', '2025-07-01', 51, 340);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (377, 4, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2025-11-10', 378, 195);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (378, 1, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2025-10-30', 205, 281);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (379, 5, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2026-03-11', 117, 246);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (380, 3, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2025-10-01', 414, 68);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (381, 1, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2025-12-06', 159, 239);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (382, 3, 'Nullam molestie nibh in lectus. Pellentesque at nulla.', '2025-10-29', 418, 469);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (383, 5, 'Etiam faucibus cursus urna.', '2025-09-03', 329, 421);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (384, 3, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2025-11-22', 121, 98);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (385, 5, 'Phasellus id sapien in sapien iaculis congue.', '2026-02-06', 21, 115);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (386, 1, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2025-03-20', 82, 381);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (387, 5, 'Proin eu mi. Nulla ac enim.', '2025-12-30', 382, 136);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (388, 3, 'Vestibulum rutrum rutrum neque.', '2025-10-22', 349, 50);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (389, 1, 'Ut at dolor quis odio consequat varius.', '2025-04-14', 456, 147);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (390, 4, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2025-07-02', 251, 432);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (391, 5, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2025-03-20', 22, 479);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (392, 4, 'In eleifend quam a odio. In hac habitasse platea dictumst.', '2025-04-19', 500, 437);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (393, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2026-01-15', 192, 470);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (394, 1, 'Nullam varius. Nulla facilisi.', '2025-12-25', 394, 175);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (395, 4, 'Nunc rhoncus dui vel sem.', '2025-04-06', 83, 174);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (396, 4, 'Donec ut dolor.', '2025-09-07', 102, 131);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (397, 3, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2025-03-30', 231, 304);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (398, 1, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '2025-06-14', 75, 312);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (399, 1, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', '2025-08-02', 246, 239);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (400, 4, 'Morbi ut odio.', '2025-09-12', 374, 158);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (401, 3, 'Nam dui.', '2025-04-19', 273, 126);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (402, 3, 'Curabitur in libero ut massa volutpat convallis.', '2026-02-09', 27, 409);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (403, 1, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2025-08-10', 343, 357);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (404, 1, 'Duis ac nibh.', '2025-03-30', 129, 222);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (405, 3, 'Vivamus in felis eu sapien cursus vestibulum.', '2025-05-01', 176, 35);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (406, 3, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '2025-11-18', 465, 360);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (407, 4, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2025-11-04', 76, 299);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (408, 3, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2025-08-22', 268, 354);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (409, 1, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2025-09-06', 471, 20);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (410, 1, 'Pellentesque ultrices mattis odio.', '2025-07-31', 67, 245);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (411, 5, 'Vestibulum ac est lacinia nisi venenatis tristique.', '2026-01-02', 489, 194);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (412, 4, 'Aliquam sit amet diam in magna bibendum imperdiet.', '2025-05-11', 323, 249);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (413, 1, 'Fusce posuere felis sed lacus.', '2025-10-17', 339, 437);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (414, 4, 'Morbi porttitor lorem id ligula.', '2025-03-22', 224, 53);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (415, 5, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2026-02-17', 157, 225);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (416, 3, 'Integer ac leo. Pellentesque ultrices mattis odio.', '2025-11-17', 43, 70);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (417, 3, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2026-01-25', 113, 41);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (418, 3, 'In hac habitasse platea dictumst.', '2026-03-03', 345, 154);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (419, 3, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2025-06-06', 48, 326);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (420, 2, 'Nulla suscipit ligula in lacus.', '2025-06-22', 284, 239);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (421, 2, 'Fusce posuere felis sed lacus.', '2025-06-07', 313, 158);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (422, 5, 'Morbi quis tortor id nulla ultrices aliquet.', '2025-04-20', 293, 126);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (423, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2025-06-19', 117, 98);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (424, 5, 'Donec ut dolor.', '2026-02-09', 290, 247);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (425, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2026-02-05', 431, 96);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (426, 4, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2025-04-27', 320, 426);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (427, 4, 'Nunc nisl.', '2026-02-16', 464, 135);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (428, 2, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2025-06-12', 466, 483);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (429, 3, 'Aenean lectus. Pellentesque eget nunc.', '2026-03-11', 441, 158);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (430, 4, 'Quisque ut erat. Curabitur gravida nisi at nibh.', '2025-05-15', 17, 212);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (431, 1, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2026-02-27', 95, 64);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (432, 5, 'Vivamus vestibulum sagittis sapien.', '2026-03-17', 37, 289);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (433, 1, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2025-09-08', 150, 288);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (434, 2, 'Donec vitae nisi.', '2025-07-04', 396, 2);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (435, 5, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2025-03-20', 434, 15);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (436, 4, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2026-01-15', 343, 161);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (437, 4, 'In quis justo.', '2026-02-02', 127, 323);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (438, 4, 'Vivamus vestibulum sagittis sapien.', '2025-12-02', 109, 173);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (439, 4, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2026-01-26', 450, 222);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (440, 4, 'Ut at dolor quis odio consequat varius.', '2025-04-20', 36, 385);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (441, 3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2025-07-21', 141, 4);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (442, 2, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2025-07-24', 436, 456);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (443, 4, 'In eleifend quam a odio. In hac habitasse platea dictumst.', '2025-05-24', 394, 237);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (444, 2, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2025-11-11', 193, 177);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (445, 5, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '2025-06-03', 271, 415);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (446, 4, 'Cras in purus eu magna vulputate luctus.', '2025-05-18', 394, 292);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (447, 1, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2025-08-22', 267, 247);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (448, 4, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2025-04-24', 445, 135);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (449, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2025-12-23', 152, 449);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (450, 5, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2026-01-29', 120, 432);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (451, 4, 'Ut at dolor quis odio consequat varius. Integer ac leo.', '2025-07-25', 365, 267);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (452, 2, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '2025-12-10', 143, 496);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (453, 5, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2025-03-23', 199, 243);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (454, 5, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2026-01-25', 77, 238);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (455, 3, 'Proin at turpis a pede posuere nonummy. Integer non velit.', '2026-01-28', 260, 421);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (456, 1, 'Suspendisse potenti.', '2026-01-17', 478, 425);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (457, 5, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '2026-01-24', 488, 122);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (458, 2, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2025-06-13', 228, 437);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (459, 5, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', '2025-08-31', 204, 269);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (460, 2, 'Sed ante.', '2025-08-30', 165, 193);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (461, 3, 'Nunc purus. Phasellus in felis.', '2025-11-27', 358, 339);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (462, 1, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2025-09-13', 320, 493);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (463, 5, 'Maecenas tincidunt lacus at velit.', '2025-12-29', 393, 12);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (464, 2, 'Nunc rhoncus dui vel sem. Sed sagittis.', '2026-01-18', 53, 240);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (465, 2, 'Proin at turpis a pede posuere nonummy.', '2026-03-01', 265, 467);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (466, 4, 'In congue. Etiam justo.', '2025-08-29', 49, 8);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (467, 1, 'Sed vel enim sit amet nunc viverra dapibus.', '2025-07-12', 155, 252);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (468, 5, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2025-07-13', 105, 83);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (469, 4, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2025-12-08', 62, 212);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (470, 5, 'Phasellus in felis. Donec semper sapien a libero.', '2026-01-11', 123, 333);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (471, 1, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2025-11-12', 489, 27);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (472, 3, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2026-01-04', 186, 231);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (473, 2, 'Vestibulum sed magna at nunc commodo placerat.', '2025-11-13', 125, 414);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (474, 4, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2025-09-22', 275, 213);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (475, 3, 'Sed ante. Vivamus tortor.', '2026-01-31', 168, 321);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (476, 3, 'Donec quis orci eget orci vehicula condimentum.', '2026-03-14', 226, 465);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (477, 5, 'Quisque porta volutpat erat.', '2025-10-04', 390, 390);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (478, 1, 'Donec quis orci eget orci vehicula condimentum.', '2025-04-28', 358, 489);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (479, 1, 'Duis mattis egestas metus. Aenean fermentum.', '2026-01-22', 257, 468);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (480, 2, 'Mauris sit amet eros.', '2026-01-25', 469, 228);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (481, 2, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '2026-02-04', 194, 40);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (482, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '2025-10-15', 137, 280);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (483, 5, 'Maecenas pulvinar lobortis est.', '2025-10-24', 68, 358);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (484, 2, 'In hac habitasse platea dictumst.', '2025-06-11', 234, 367);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (485, 3, 'Praesent blandit. Nam nulla.', '2025-05-10', 466, 199);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (486, 1, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2026-02-05', 445, 387);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (487, 2, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2025-06-30', 407, 487);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (488, 2, 'Quisque ut erat.', '2025-10-09', 264, 481);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (489, 4, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2025-08-31', 490, 179);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (490, 5, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2025-03-25', 370, 387);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (491, 2, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '2025-09-03', 438, 163);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (492, 2, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2025-07-31', 29, 425);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (493, 4, 'Integer tincidunt ante vel ipsum.', '2026-03-05', 69, 323);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (494, 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2025-04-07', 315, 95);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (495, 1, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2026-03-06', 93, 468);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (496, 5, 'Aliquam erat volutpat. In congue.', '2026-03-09', 249, 272);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (497, 5, 'Duis bibendum.', '2025-11-08', 463, 77);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (498, 5, 'Suspendisse accumsan tortor quis turpis.', '2025-11-28', 471, 172);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (499, 3, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2026-02-25', 87, 412);
insert into PRODUCT_REVIEWS (ReviewID, Rating, Comment, ReviewDate, ProductID, CustomerID) values (500, 3, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '2026-03-12', 13, 15);
