CREATE TABLE CUSTOMERS
(
  CustomerID INT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Phone VARCHAR(20) NOT NULL,
  RegistrationDate DATE NOT NULL,
  PRIMARY KEY (CustomerID)
);

CREATE TABLE SUPPLIERS
(
  SupplierID INT NOT NULL,
  CompanyName VARCHAR(100) NOT NULL,
  ContactName VARCHAR(100) NOT NULL,
  ContactPhone VARCHAR(20) NOT NULL,
  PRIMARY KEY (SupplierID)
);

CREATE TABLE CATEGORIES
(
  CategoryID INT NOT NULL,
  CategoryName VARCHAR(50) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  PRIMARY KEY (CategoryID)
);

CREATE TABLE WAREHOUSES
(
  WarehouseID INT NOT NULL,
  Location VARCHAR(100) NOT NULL,
  Capacity INT NOT NULL CHECK (Capacity >= 0),
  PRIMARY KEY (WarehouseID)
);

CREATE TABLE PRODUCTS
(
  ProductID INT NOT NULL,
  ProductName VARCHAR(100) NOT NULL,
  Price NUMERIC(10,2) NOT NULL CHECK (Price >= 0),
  StockQuantity INT NOT NULL CHECK (StockQuantity >= 0),
  CategoryID INT NOT NULL,
  SupplierID INT NOT NULL,
  WarehouseID INT NOT NULL,
  PRIMARY KEY (ProductID),
  FOREIGN KEY (CategoryID) REFERENCES CATEGORIES(CategoryID),
  FOREIGN KEY (SupplierID) REFERENCES SUPPLIERS(SupplierID),
  FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSES(WarehouseID)
);

CREATE TABLE SHIPPERS
(
  ShipperID INT NOT NULL,
  CompanyName VARCHAR(100) NOT NULL,
  Website VARCHAR(255),
  ContactPhone VARCHAR(20) NOT NULL,
  PRIMARY KEY (ShipperID)
);

CREATE TABLE COUPONS
(
  CouponID INT NOT NULL,
  CouponCode VARCHAR(20) NOT NULL UNIQUE,
  DiscountPercent INT NOT NULL CHECK (DiscountPercent BETWEEN 1 AND 100),
  ExpiryDate DATE NOT NULL,
  PRIMARY KEY (CouponID)
);

CREATE TABLE EMPLOYEES
(
  EmployeeID INT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Role VARCHAR(50) NOT NULL,
  HireDate DATE NOT NULL,
  WarehouseID INT NOT NULL,
  PRIMARY KEY (EmployeeID),
  FOREIGN KEY (WarehouseID) REFERENCES WAREHOUSES(WarehouseID)
);

CREATE TABLE ORDERS
(
  OrderID INT NOT NULL,
  OrderDate DATE NOT NULL,
  ShippingAddress VARCHAR(255) NOT NULL,
  Status VARCHAR(20) NOT NULL CHECK (Status IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')),
  ShipperID INT NOT NULL,
  CustomerID INT NOT NULL,
  CouponID INT, 
  EmployeeID INT NOT NULL,
  PRIMARY KEY (OrderID),
  FOREIGN KEY (ShipperID) REFERENCES SHIPPERS(ShipperID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID),
  FOREIGN KEY (CouponID) REFERENCES COUPONS(CouponID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES(EmployeeID)
);

CREATE TABLE PRODUCT_REVIEWS
(
  ReviewID INT NOT NULL,
  Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
  Comment VARCHAR(500),
  ReviewDate DATE NOT NULL,
  ProductID INT NOT NULL,
  CustomerID INT NOT NULL,
  PRIMARY KEY (ReviewID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);

CREATE TABLE ORDER_ITEMS
(
  Quantity INT NOT NULL CHECK (Quantity > 0),
  UnitPrice NUMERIC(10,2) NOT NULL CHECK (UnitPrice >= 0),
  ProductID INT NOT NULL,
  OrderID INT NOT NULL,
  PRIMARY KEY (ProductID, OrderID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);